import { GoogleGenAI } from '@google/genai';
import type { Issue, TimelineEvent, ZoneType } from '../types';
import { computeImpact, slaHoursForImpact } from './impactEngine';
import { summariseIssue, type ToolContext } from './agentTools';
import { nextId } from '../data/seed';

// ---------------------------------------------------------------------------
// Browser-side ToolContext for the AI Studio single-app deploy (no backend).
// Operates on the in-memory store via the callbacks passed from React.
// ---------------------------------------------------------------------------

const WARD_IDS: Record<string, number> = { Horamavu: 24, Thanisandra: 25, Jnanabharathi: 45, Bellandur: 112 };

export interface ClientCtxHooks {
  getIssues: () => Issue[];
  addIssue: (i: Issue) => void;
  updateIssue: (id: string, patch: Partial<Issue>, persist?: boolean) => void;
  ai: GoogleGenAI | null;
}

export function buildClientContext(h: ClientCtxHooks): ToolContext {
  const find = (id: string) => h.getIssues().find((i) => i.id.toLowerCase() === String(id).toLowerCase());
  return {
    listIssues({ ward, status, minImpact, limit = 5 }) {
      let list = [...h.getIssues()].sort((a, b) => b.impact.total - a.impact.total);
      if (ward) list = list.filter((i) => i.ward.toLowerCase() === ward.toLowerCase());
      if (status) list = list.filter((i) => i.status.toLowerCase() === status.toLowerCase());
      if (typeof minImpact === 'number') list = list.filter((i) => i.impact.total >= minImpact);
      return list.slice(0, limit).map(summariseIssue);
    },
    getIssue({ id }) {
      const i = find(id);
      return i ? summariseIssue(i) : { error: `No issue ${id}` };
    },
    createReport(a) {
      const ward = a.ward ?? 'Jnanabharathi';
      const zone = (a.zone ?? 'Arterial Road') as ZoneType;
      const severity = (a.severity ?? 'Shallow') as Issue['severity'];
      const depth = severity === 'Critical' ? 22 : severity === 'Deep' ? 13 : severity === 'Shallow' ? 6 : 2;
      const trafficScore = 40 + Math.round(Math.random() * 55);
      const rainRisk7d = 25 + Math.round(Math.random() * 60);
      const impact = computeImpact({ severity, depthCm: depth, trafficScore, zone, rainRisk7d });
      const issue: Issue = {
        id: nextId(), imageUrl: '',
        damageType: a.damageType ?? 'Other', severity, status: 'Reported',
        ward, wardId: WARD_IDS[ward] ?? 45, location: a.location ?? 'Unspecified',
        lat: 12.94 + Math.random() * 0.1, lng: 77.5 + Math.random() * 0.18,
        zone, trafficScore, rainRisk7d, confirmations: 1, reportedAt: 'just now',
        analysis: {
          isCivicIssue: true, damageType: a.damageType ?? 'Other', severity,
          estimatedDepthCm: depth, widthEstimate: '~0.5 m', rootCause: 'Reported via Civic Copilot.',
          repairBrief: a.description ?? 'Inspect and patch.', materials: ['Hot-mix asphalt', 'Tack coat'],
          estimatedCostRange: [3000, 8000], confidence: 75,
          publicSummary: `${severity} ${a.damageType ?? 'issue'} at ${a.location ?? 'location'}.`,
        },
        impact, slaHours: slaHoursForImpact(impact.total), ageHours: 0,
        anonymous: false, channel: 'App',
        timeline: [{ status: 'Reported', label: 'Filed by Civic Copilot', timestamp: 'just now', detail: 'text report' }],
      };
      h.addIssue(issue);
      return summariseIssue(issue);
    },
    dispatchCrew({ id }) {
      const issue = find(id);
      if (!issue) return { error: `No issue ${id}` };
      const ev: TimelineEvent = { status: 'Work Order', label: 'Work order generated by Copilot', timestamp: 'just now', detail: 'Namma Civil Crew' };
      h.updateIssue(issue.id, { status: 'Work Order', contractor: 'Namma Civil Crew', timeline: [...issue.timeline, ev] });
      return { id: issue.id, status: 'Work Order', contractor: 'Namma Civil Crew', message: 'Work order created.' };
    },
    escalateIssue({ id }) {
      const issue = find(id);
      if (!issue) return { error: `No issue ${id}` };
      const ev: TimelineEvent = { status: issue.status, label: 'Escalated to ward councillor', timestamp: 'just now', detail: 'via Copilot' };
      h.updateIssue(issue.id, { timeline: [...issue.timeline, ev] });
      return { id: issue.id, message: `Escalated to ${issue.ward} ward councillor.` };
    },
    getWardScorecard({ ward }) {
      const issues = h.getIssues();
      const names = ['Horamavu', 'Thanisandra', 'Jnanabharathi', 'Bellandur'];
      return names
        .filter((n) => !ward || n.toLowerCase() === ward.toLowerCase())
        .map((n) => ({ ward: n, openNow: issues.filter((i) => i.ward === n && i.status !== 'Resolved').length }));
    },
    async searchCivicInfo({ query }) {
      if (!h.ai) return { answer: 'Search needs a Gemini connection (demo mode).', sources: [] };
      try {
        const res = await h.ai.models.generateContent({
          model: 'gemini-2.5-flash', contents: query,
          config: { tools: [{ googleSearch: {} }], temperature: 0.2 },
        });
        const chunks = res.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
        const sources = chunks
          .map((c: any) => ({ title: c.web?.title ?? 'source', uri: c.web?.uri ?? '' }))
          .filter((s: any) => s.uri).slice(0, 4);
        return { answer: (res.text ?? '').trim(), sources };
      } catch (e) {
        return { answer: `Search unavailable (${(e as Error).message}).`, sources: [] };
      }
    },
    async locationContext({ query }) {
      if (!h.ai) return { answer: 'Location lookup needs a Gemini connection (demo mode).', sources: [] };
      for (const tool of [{ googleMaps: {} }, { googleSearch: {} }]) {
        try {
          const res = await h.ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Describe the area around: ${query}. Note nearby schools, hospitals, main roads or markets relevant to civic risk.`,
            config: { tools: [tool as any], temperature: 0.2 },
          });
          const chunks = res.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
          const sources = chunks
            .map((c: any) => ({ title: c.web?.title ?? c.maps?.title ?? 'source', uri: c.web?.uri ?? c.maps?.uri ?? '' }))
            .filter((s: any) => s.uri).slice(0, 4);
          return { answer: (res.text ?? '').trim(), sources };
        } catch { /* try next */ }
      }
      return { answer: 'Location grounding unavailable right now.', sources: [] };
    },
    async readUrl({ url, question }) {
      if (!h.ai) return { answer: 'URL reading needs a Gemini connection (demo mode).', sources: [] };
      try {
        const res = await h.ai.models.generateContent({
          model: 'gemini-2.5-flash',
          contents: `${question ?? 'Summarise the key points of this page'}: ${url}`,
          config: { tools: [{ urlContext: {} }], temperature: 0.2 },
        });
        return { answer: (res.text ?? '').trim(), sources: [{ title: url, uri: url }] };
      } catch (e) {
        return { answer: `Could not read that URL (${(e as Error).message}).`, sources: [] };
      }
    },
  };
}
