import { GoogleGenAI } from '@google/genai';
import type { Issue, TimelineEvent, ZoneType } from '../types';
import { computeImpact, slaHoursForImpact } from '../services/impactEngine';
import { runAgent, type ChatMsg, type AgentResult } from '../services/agent';
import { summariseIssue, type ToolContext } from '../services/agentTools';
import * as store from './store.js';

// ---------------------------------------------------------------------------
// Server agent: ToolContext backed by the persistent store. searchCivicInfo
// performs a real Google Search-grounded Gemini call.
// ---------------------------------------------------------------------------

const MODEL = 'gemini-2.5-flash';

function getAI() {
  return new GoogleGenAI({ apiKey: process.env.API_KEY || process.env.GEMINI_API_KEY || '' });
}

const WARD_IDS: Record<string, number> = { Horamavu: 24, Thanisandra: 25, Jnanabharathi: 45, Bellandur: 112 };

function buildContext(ai: GoogleGenAI): ToolContext {
  return {
    listIssues({ ward, status, minImpact, limit = 5 }) {
      let list = store.getIssues();
      if (ward) list = list.filter((i) => i.ward.toLowerCase() === ward.toLowerCase());
      if (status) list = list.filter((i) => i.status.toLowerCase() === status.toLowerCase());
      if (typeof minImpact === 'number') list = list.filter((i) => i.impact.total >= minImpact);
      return list.slice(0, limit).map(summariseIssue);
    },
    getIssue({ id }) {
      const i = store.getIssue(id);
      return i ? summariseIssue(i) : { error: `No issue ${id}` };
    },
    createReport(a) {
      const ward = a.ward ?? 'Jnanabharathi';
      const zone = (a.zone ?? 'Arterial Road') as ZoneType;
      const severity = (a.severity ?? 'Shallow') as Issue['severity'];
      const depth = severity === 'Critical' ? 22 : severity === 'Deep' ? 13 : severity === 'Shallow' ? 6 : 2;
      const trafficScore = 40 + Math.round(Math.random() * 55);
      const rainRisk7d = 25 + Math.round(Math.random() * 60);
      const impact = computeImpact({ severity, depthCm: depth, trafficScore, zone, rainRisk7d });
      const issue: Issue = {
        id: store.nextId(),
        imageUrl: '',
        damageType: a.damageType ?? 'Other',
        severity, status: 'Reported',
        ward, wardId: WARD_IDS[ward] ?? 45, location: a.location ?? 'Unspecified',
        lat: 12.94 + Math.random() * 0.1, lng: 77.5 + Math.random() * 0.18,
        zone, trafficScore, rainRisk7d, confirmations: 1,
        reportedAt: 'just now',
        analysis: {
          isCivicIssue: true, damageType: a.damageType ?? 'Other', severity,
          estimatedDepthCm: depth, widthEstimate: '~0.5 m',
          rootCause: 'Reported via Civic Copilot.',
          repairBrief: a.description ?? 'Inspect and patch.',
          materials: ['Hot-mix asphalt', 'Tack coat'],
          estimatedCostRange: [3000, 8000], confidence: 75,
          publicSummary: `${severity} ${a.damageType ?? 'issue'} at ${a.location ?? 'location'}.`,
        },
        impact, slaHours: slaHoursForImpact(impact.total), ageHours: 0,
        anonymous: false, channel: 'App', contractor: undefined,
        timeline: [{ status: 'Reported', label: 'Filed by Civic Copilot', timestamp: 'just now', detail: 'text report' }],
      };
      store.addIssue(issue);
      return summariseIssue(issue);
    },
    dispatchCrew({ id }) {
      const issue = store.getIssue(id);
      if (!issue) return { error: `No issue ${id}` };
      const c = store.pickContractor();
      const ev: TimelineEvent = { status: 'Work Order', label: 'Work order generated by Copilot', timestamp: 'just now', detail: c?.name };
      const updated = store.updateIssue(id, { status: 'Work Order', contractor: c?.name, timeline: [...issue.timeline, ev] });
      return { id, status: 'Work Order', contractor: c?.name, message: `Work order created, assigned ${c?.name}.`, impact: updated?.impact.total };
    },
    escalateIssue({ id }) {
      const issue = store.getIssue(id);
      if (!issue) return { error: `No issue ${id}` };
      const ev: TimelineEvent = { status: issue.status, label: 'Escalated to ward councillor', timestamp: 'just now', detail: 'via Copilot' };
      store.updateIssue(id, { timeline: [...issue.timeline, ev] });
      return { id, message: `Issue ${id} escalated to the ${issue.ward} ward councillor.` };
    },
    getWardScorecard({ ward }) {
      const wards = store.getWards();
      const issues = store.getIssues();
      const rows = (ward ? wards.filter((w) => w.name.toLowerCase() === ward.toLowerCase()) : wards).map((w) => ({
        ward: w.name, wardId: w.id, resolutionRate: w.resolutionRate, avgResponseDays: w.avgResponseDays,
        openNow: issues.filter((i) => i.ward === w.name && i.status !== 'Resolved').length,
      }));
      return rows;
    },
    async searchCivicInfo({ query }) {
      try {
        const res = await ai.models.generateContent({
          model: MODEL,
          contents: query,
          config: { tools: [{ googleSearch: {} }], temperature: 0.2 },
        });
        const chunks = res.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
        const sources = chunks
          .map((c: any) => ({ title: c.web?.title ?? c.web?.uri ?? 'source', uri: c.web?.uri ?? '' }))
          .filter((s: any) => s.uri)
          .slice(0, 4);
        return { answer: (res.text ?? '').trim(), sources };
      } catch (e) {
        return { answer: `Could not search right now (${(e as Error).message}).`, sources: [] };
      }
    },
    async locationContext({ query }) {
      // Prefer Google Maps grounding; fall back to Search grounding if unavailable.
      for (const tool of [{ googleMaps: {} }, { googleSearch: {} }]) {
        try {
          const res = await ai.models.generateContent({
            model: MODEL,
            contents: `Describe the area around: ${query}. Note nearby schools, hospitals, main roads or markets relevant to civic risk.`,
            config: { tools: [tool as any], temperature: 0.2 },
          });
          const chunks = res.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
          const sources = chunks
            .map((c: any) => ({ title: c.web?.title ?? c.maps?.title ?? 'source', uri: c.web?.uri ?? c.maps?.uri ?? '' }))
            .filter((s: any) => s.uri).slice(0, 4);
          return { answer: (res.text ?? '').trim(), sources, grounding: 'googleMaps' in tool ? 'maps' : 'search' };
        } catch { /* try next tool */ }
      }
      return { answer: 'Location grounding unavailable right now.', sources: [] };
    },
    async readUrl({ url, question }) {
      try {
        const res = await ai.models.generateContent({
          model: MODEL,
          contents: `${question ?? 'Summarise the key points of this page'}: ${url}`,
          config: { tools: [{ urlContext: {} }], temperature: 0.2 },
        });
        return { answer: (res.text ?? '').trim(), sources: [{ title: url, uri: url }] };
      } catch (e) {
        return { answer: `Could not read that URL (${(e as Error).message}).`, sources: [] };
      }
    },
  };
}

export async function runServerAgent(history: ChatMsg[]): Promise<AgentResult> {
  const ai = getAI();
  return runAgent(ai, history, buildContext(ai));
}
